[mypy]
python_version = 3.10
ignore_missing_imports = True
allow_untyped_decorators = True
allow_untyped_calls = True
allow_untyped_defs = True
warn_unused_configs = False
exclude = 
    src/async_repository_worker/bot.py
    src/async_repository_worker/main.py
    src/async_repository_worker/search.py
    src/async_repository_worker/database.py